baseline:
  data.train.dataset: wikiann
  data.train.subset: 1.0
  data.eval.dataset: wikiann
  data.eval.subset: 1.0
  train.epochs: 30

sweep:
  product_model.num_subspaces: [3]
  #product_model.latent_dim: [128, 256, 384]
  product_model.losses.geom_sparsity: [0.0, 0.01, 0.1]
  product_model.losses.geom_orthogonality: [0.0, 0.01, 0.1]
  product_model.betas.dis_spar: [0.01, 0.1, 1.0]