defaults:
  - default
  - _self_

product_model:
  input_dim: 384
  latent_dim: 256
  encoder_hidden: 512
  projector_hidden: 256
  num_subspaces: 4
  margin: 0.5
  temperature: 1.0
  betas:
    dis_spar: 0.1
    consistency: 0.1
    regularization: 0.1
  warmup_epochs:
    consistency: 5
    distance: 5
  losses:
    geom_sparsity: 0.05
    geom_orthogonality: 0.05
  optim:
    lr: 5e-4
    weight_decay: 1e-5
    betas: [0.9, 0.999]
